// Auto-generated by Yeppp.CLR.csproj
[assembly: System.Reflection.AssemblyVersion("1.0.1.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.1.0")]
#pragma warning disable 1607
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.1 Pre-Release")]
