//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWSIM.UI.Forms.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWSIM.UI.Forms.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About DWSIM Simulator.
        /// </summary>
        internal static string AboutDWSIM {
            get {
                return ResourceManager.GetString("AboutDWSIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close DWSIM.
        /// </summary>
        internal static string AppExit {
            get {
                return ResourceManager.GetString("AppExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version: .
        /// </summary>
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All opened flowsheets will be closed and you&apos;ll lose any unsaved work. Continue?.
        /// </summary>
        internal static string ConfirmAppExit {
            get {
                return ResourceManager.GetString("ConfirmAppExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll lose any unsaved work. Continue?.
        /// </summary>
        internal static string ConfirmFlowsheetExit {
            get {
                return ResourceManager.GetString("ConfirmFlowsheetExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup inlet and outlet port connections for the selected object. Select a blank item from the list to disconnect the port from the current connected object..
        /// </summary>
        internal static string ConnectorsEditorDescription {
            get {
                return ResourceManager.GetString("ConnectorsEditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWSIM Launcher.
        /// </summary>
        internal static string DWSIMLauncher {
            get {
                return ResourceManager.GetString("DWSIMLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWSIM is released under the GPL v3 license:.
        /// </summary>
        internal static string DWSIMLicense {
            get {
                return ResourceManager.GetString("DWSIMLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Flowsheet.
        /// </summary>
        internal static string FlowsheetExit {
            get {
                return ResourceManager.GetString("FlowsheetExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework Version: .
        /// </summary>
        internal static string FrameworkVersion {
            get {
                return ResourceManager.GetString("FrameworkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is released under the terms of the GNU General Public License (GPL) version 3. See specific licenses for external components on the &apos;About&apos; box..
        /// </summary>
        internal static string GPLNotice {
            get {
                return ResourceManager.GetString("GPLNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Components....
        /// </summary>
        internal static string LoadingComponents {
            get {
                return ResourceManager.GetString("LoadingComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Compound.
        /// </summary>
        internal static string NewCompound {
            get {
                return ResourceManager.GetString("NewCompound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Data Regression.
        /// </summary>
        internal static string NewDataRegression {
            get {
                return ResourceManager.GetString("NewDataRegression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Simulation.
        /// </summary>
        internal static string NewSimulation {
            get {
                return ResourceManager.GetString("NewSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Saved File.
        /// </summary>
        internal static string OpenSavedFile {
            get {
                return ResourceManager.GetString("OpenSavedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Window_GeneralSettings_Backup {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Copies.
        /// </summary>
        internal static string Window_GeneralSettings_BackupCopies {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_BackupCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Interval (minutes).
        /// </summary>
        internal static string Window_GeneralSettings_BackupInterval {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_BackupInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Solver on Calculation Error.
        /// </summary>
        internal static string Window_GeneralSettings_BreakOnException {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_BreakOnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Options.
        /// </summary>
        internal static string Window_GeneralSettings_ControlOptions {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_ControlOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFD Designer.
        /// </summary>
        internal static string Window_GeneralSettings_Designer {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Anti-Aliasing.
        /// </summary>
        internal static string Window_GeneralSettings_EnableAntiAliasing {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_EnableAntiAliasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Backup Copies.
        /// </summary>
        internal static string Window_GeneralSettings_EnableBackupCopies {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_EnableBackupCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable CPU Parallel Processing.
        /// </summary>
        internal static string Window_GeneralSettings_EnableCPUParallelProcessing {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_EnableCPUParallelProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CPU SIMD Instructions.
        /// </summary>
        internal static string Window_GeneralSettings_EnableCPUSIMDAccel {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_EnableCPUSIMDAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GPU Parallel Processing.
        /// </summary>
        internal static string Window_GeneralSettings_EnableGPUAccel {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_EnableGPUAccel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowsheet.
        /// </summary>
        internal static string Window_GeneralSettings_Flowsheet {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_Flowsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscelaneous.
        /// </summary>
        internal static string Window_GeneralSettings_Misc {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Backup Folder.
        /// </summary>
        internal static string Window_GeneralSettings_PurgeBackupFolder {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_PurgeBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solver.
        /// </summary>
        internal static string Window_GeneralSettings_Solver {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_Solver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        internal static string Window_GeneralSettings_Title {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Compounds.
        /// </summary>
        internal static string Window_GeneralSettings_UserComps {
            get {
                return ResourceManager.GetString("Window_GeneralSettings_UserComps", resourceCulture);
            }
        }
    }
}
