'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DWSIM.Thermodynamics.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Um Pacote de Propriedades simplificado para cálculos rápidos de processo envolvendo fluidos de petróleo caracterizados por propriedades simples, tais como densidades e razão gás-óleo..
        '''</summary>
        Friend Shared ReadOnly Property DescBOPP() As String
            Get
                Return ResourceManager.GetString("DescBOPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Um Pacote de Propriedades CAPE-OPEN é uma coleção completa, consistente e reutilizável de métodos, compostos e parâmetros do modelo de cálculo de qualquer de um conjunto de propriedades físicas conhecidas para as Phases de um material. Ele inclui todos os métodos e compostos puros dados, juntamente com as normas pertinentes à mistura e parâmetros de interação. Um Pacote de Propriedades normalmente cobre apenas um pequeno subconjunto dos compostos e métodos acessíveis através de um Sistema de Propriedades Fí [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DescCOPP() As String
            Get
                Return ResourceManager.GetString("DescCOPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CoolProp is an open-source database of fluid and humid air properties, formulated based on the most accurate formulations in open literature. It has been validated against the most accurate data available from the relevant references..
        '''</summary>
        Friend Shared ReadOnly Property DescCPPP() As String
            Get
                Return ResourceManager.GetString("DescCPPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades que usa o modelo empírico de Chao e Seader para o cálculo do coeficiente de partição K no equilíbrio líquido-vapor. Todas as outras propriedades termodinâmicas (entalpia, entropia, Cp/Cv, etc.) são calculadas pelo modelo de Lee e Kesler..
        '''</summary>
        Friend Shared ReadOnly Property DescCSLKPP() As String
            Get
                Return ResourceManager.GetString("DescCSLKPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades que utiliza o método COSMO-SAC implementado na biblioteca JCOSMO por Rafael Soares e Renan Gerber para a predição do coeficiente de atividade dos componentes na Phase líquida. As Entalpias, Entropias e Capacidades Caloríficas residuais são calculadas a partir do modelo de Lee-Kesler. A Phase vapor é modelada através da EDE Peng-Robinson..
        '''</summary>
        Friend Shared ReadOnly Property DescCSPP() As String
            Get
                Return ResourceManager.GetString("DescCSPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This model is a combination of the extended UNIQUAC model for electrolytes and the Soave–Redlich–Kwong cubic equation of state. The model has been applied to aqueous systems containing ammonia and/or carbon dioxide along with various salts. Model parameters valid in the temperature range 0–110°C, the pressure range from 0–100 bar, and the concentration range up to approximately 80 molal ammonia are given. The model parameters were evaluated on the basis of more than 7000 experimental data points..
        '''</summary>
        Friend Shared ReadOnly Property DescEUPP() As String
            Get
                Return ResourceManager.GetString("DescEUPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FPROPS is a free open-source C-based library for high-accuracy evaluation of thermodynamic properties for a number of pure substances. It makes use of published data for the Helmholtz fundamental equation for those substances.
        '''
        '''FPROPS is Copyright (C) 2011 - Carnegie Mellon University.
        '''</summary>
        Friend Shared ReadOnly Property DescFPP() As String
            Get
                Return ResourceManager.GetString("DescFPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades que usa o modelo empírico de Grayson e Streed para o cálculo do coeficiente de partição K no equilíbrio líquido-vapor. Todas as outras propriedades termodinâmicas (entalpia, entropia, Cp/Cv, etc.) são calculadas pelo modelo de Lee e Kesler..
        '''</summary>
        Friend Shared ReadOnly Property DescGSLKPP() As String
            Get
                Return ResourceManager.GetString("DescGSLKPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neste Pacote de Propriedades, a Equação baseada na Teoria dos Estados Correspondentes desenvolvida por Lee e Kesler foi aprimorada por Plöcker para cálculo da fugacidade dos componentes em misturas assimétricas. Aqui, todas as propriedades são calculadas pela Equação LKP, incluindo os K-values..
        '''</summary>
        Friend Shared ReadOnly Property DescLKPPP() As String
            Get
                Return ResourceManager.GetString("DescLKPPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades que utiliza o método de Contribuição de Grupos UNIFAC Modificado (Dortmund) para a modelagem da Phase líquida. As Entalpias, Entropias e Capacidades Caloríficas residuais são calculadas a partir do modelo de Lee-Kesler..
        '''</summary>
        Friend Shared ReadOnly Property DescMUPP() As String
            Get
                Return ResourceManager.GetString("DescMUPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neste Pacote de Propriedades, o coeficiente de atividade da Phase líquida é calculado através do modelo NRTL (Non-Random Two-Liquid). Opcionalmente, a fugacidade da Phase vapor é calculada através da EDE Peng-Robinson. As entalpias de ambas as Phases são calculadas pela equação Lee-Kesler. Outras propriedades termodinâmicas são calculadas pela EDE Peng-Robinson. .
        '''</summary>
        Friend Shared ReadOnly Property DescNRTLPP() As String
            Get
                Return ResourceManager.GetString("DescNRTLPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Novos parâmetros do modelo de previsão de propriedade modificado UNIFAC são relatados para 89 grupos principais e 984 interações de grupo em grupo, utilizando dados de equilíbrio de Phases criticamente avaliados incluindo equilíbrio líquido-vapor (ELV), o equilíbrio líquido-líquido (ELL), equilíbrio sólido-líquido (ESL) , excesso de entalpia (HE), coeficiente de atividade infinita de diluição (AINF) e dados de excesso de capacidade de calor (CPE). Os parâmetros obtidos são recomendados principalmente para c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DescNUPP() As String
            Get
                Return ResourceManager.GetString("DescNUPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Perturbed Chain SAFT model is a state-of-the-art, engineering-like equation of state. It is designed for modelling mixtures of all types of substances: gases, solvents and polymers.
        '''
        '''Perturbed-Chain SAFT is suitable for the calculation of phase equilibria and thermophysical properties of pure components and mixtures. It has been tested against experimental data for numerous systems and found to give excellent results. When compared to other equations of state, we find Perturbed-Chain SAFT to be more pre [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DescPCSAFTPP() As String
            Get
                Return ResourceManager.GetString("DescPCSAFTPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades que utiliza a EDE Peng-Robinson e considera água totalmente imiscível com hidrocarbonetos, separando-se em uma Phase isolada. Também utiliza translação no cálculo do volume molar para uma melhor predição da densidade de líquidos..
        '''</summary>
        Friend Shared ReadOnly Property DescPengRobinsonIWVTPP() As String
            Get
                Return ResourceManager.GetString("DescPengRobinsonIWVTPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades com a EDE Peng-Robinson e suporte a mais de uma Phase líquida..
        '''</summary>
        Friend Shared ReadOnly Property DescPengRobinsonMP() As String
            Get
                Return ResourceManager.GetString("DescPengRobinsonMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades que utiliza a EE Peng-Robinson. Indicado para uso com hidrocarbonetos e não-condensáveis..
        '''</summary>
        Friend Shared ReadOnly Property DescPengRobinsonPP() As String
            Get
                Return ResourceManager.GetString("DescPengRobinsonPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neste Pacote de Propriedades, as Entalpias, Entropias e Capacidades Caloríficas residuais são calculadas a partir do modelo de Lee-Kesler..
        '''</summary>
        Friend Shared ReadOnly Property DescPRLK() As String
            Get
                Return ResourceManager.GetString("DescPRLK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PRSV2 EOS com três parâmetros por componente (k1, k2 e k3) e dois parâmetros de interação binária do tipo Margules (kij e kji).
        '''
        '''A modificação para o termo atrativo na equação Peng-Robinson publicado por Stryjek e Vera em 1986 (PRSV) melhorou significativamente a precisão do modelo através da introdução de um parâmetro ajustável para o componente puro e modificando o ajuste polinomial do fator acêntrico. Uma modificação posterior, publicada em 1986 (PRSV2), melhorou a precisão dos modelos através da introdu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DescPRSV2PP() As String
            Get
                Return ResourceManager.GetString("DescPRSV2PP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PRSV2 EOS com três parâmetros por componente (k1, k2 e k3) e dois parâmetros de interação binária do tipo Margules (kij e kji).
        '''
        '''A modificação para o termo atrativo na equação Peng-Robinson publicado por Stryjek e Vera em 1986 (PRSV) melhorou significativamente a precisão do modelo através da introdução de um parâmetro ajustável para o componente puro e modificando o ajuste polinomial do fator acêntrico. Uma modificação posterior, publicada em 1986 (PRSV2), melhorou a precisão dos modelos através da introdu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DescPRSV2VLPP() As String
            Get
                Return ResourceManager.GetString("DescPRSV2VLPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utiliza a EE Peng-Robinson com a regra de mistura de Wong e Sandler. A EnergyFlow de Gibbs em excesso (GE/RT) é calculada pelo modelo UNIFAC.
        '''Recomendada para uso com misturas binárias ou ternárias de substâncias polares em altas pressões e temperaturas. Para cálculo do ELV de hidrocarbonetos e/ou não-condensáveis, utilize a EE PR ou SRK..
        '''</summary>
        Friend Shared ReadOnly Property DescPRWSPP() As String
            Get
                Return ResourceManager.GetString("DescPRWSPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1. Descrição.
        '''</summary>
        Friend Shared ReadOnly Property Descrio1() As String
            Get
                Return ResourceManager.GetString("Descrio1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades de referência, onde o equilíbrio termodinâmico é calculado pela Lei de Raoult. As Entalpias, Entropias e Capacidades Caloríficas residuais são consideradas iguais a zero. A Entalpia da Phase Líquida utiliza os valores de Delta-H de Vaporização experimentais ou calculados no caso dos Pseudo-componentes / Hipotéticos..
        '''</summary>
        Friend Shared ReadOnly Property DescRPP() As String
            Get
                Return ResourceManager.GetString("DescRPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Este Pacote de Propriedades contém rotinas para calcular propriedades da água do mar utilizando os procedimentos constantes na especificação IAPWS-08 (&quot;Release on the IAPWS Formulation 2008 for the Thermodynamic Properties of Seawater&quot;)..
        '''</summary>
        Friend Shared ReadOnly Property DescSEAPP() As String
            Get
                Return ResourceManager.GetString("DescSEAPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades que utiliza a EE Redlich-Kwong modificada por Soave. Indicado para uso com hidrocarbonetos e não-condensáveis.
        '''As propriedades são calculadas diretamente através da equação de estado e/ou de dados experimentais, exceto:
        '''Massa Específica da Phase Líquida: Método de Rackett
        '''Condutividade Térmica da Phase Líquida: Método de Latini et al
        '''Condutividade Térmica da Phase Vapor: Método de Ely e Hanley
        '''Viscosidade da Phase Vapor: Método Jossi-Stiel-Thodos
        '''Tensão Superficial da Phase Líquida: M [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DescSoaveRedlichKwongSRK() As String
            Get
                Return ResourceManager.GetString("DescSoaveRedlichKwongSRK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Sour Water Property Package is based on the SWEQ model described in the USEPA Report EPA-600/2-80-067: &apos;A new correlation of NH3, CO2, and H2S volatility data from aqueous sour water systems&apos;, by Wilson, Grant M., available online at http://nepis.epa.gov/Exe/ZyPDF.cgi?Dockey=9101B309.PDF  
        '''
        '''In this model, chemical and physical equilibria of NH3, CO2, and H2S in sour water systems including the effects of release by caustic (NaOH) addition are considered. The original model is applicable for temperatures [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DescSourWaterPP() As String
            Get
                Return ResourceManager.GetString("DescSourWaterPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades com suporte a flash multifásico utilizando a EDE SRK..
        '''</summary>
        Friend Shared ReadOnly Property DescSRKMP() As String
            Get
                Return ResourceManager.GetString("DescSRKMP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades para uso exclusivo com Água (IAPWS-97).
        '''</summary>
        Friend Shared ReadOnly Property DescSteamTablesPP() As String
            Get
                Return ResourceManager.GetString("DescSteamTablesPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neste Pacote de Propriedades, o coeficiente de atividade da Phase líquida é calculado através do modelo UNIQUAC. Opcionalmente, a fugacidade da Phase vapor é calculada através da EDE Peng-Robinson. As entalpias de ambas as Phases são calculadas pela equação Lee-Kesler. Outras propriedades termodinâmicas são calculadas pela EDE Peng-Robinson..
        '''</summary>
        Friend Shared ReadOnly Property DescUNIQUACPP() As String
            Get
                Return ResourceManager.GetString("DescUNIQUACPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pacote de Propriedades que utiliza o método de Contribuição de Grupos UNIFAC para a modelagem da Phase líquida. As Entalpias, Entropias e Capacidades Caloríficas residuais são calculadas a partir do modelo de Lee-Kesler. A Phase vapor é modelada através da EDE Peng-Robinson. Recomendado para uso com os Componentes Hipotéticos..
        '''</summary>
        Friend Shared ReadOnly Property DescUPP() As String
            Get
                Return ResourceManager.GetString("DescUPP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Um ou ambos os valores das variáveis especificadas para o cálculo flash está (estão) inválido(s). Por favor verifique a Operação Unitária associada ou suas correntes de entrada para encontrar possíveis erros nas suas propriedades especificadas ou calculadas..
        '''</summary>
        Friend Shared ReadOnly Property ErrorInvalidFlashSpecValue() As String
            Get
                Return ResourceManager.GetString("ErrorInvalidFlashSpecValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carrega informações sobre substâncias e condições de fluxo de matéria.
        '''</summary>
        Friend Shared ReadOnly Property MSTR_Desc() As String
            Get
                Return ResourceManager.GetString("MSTR_Desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Corrente de Matéria.
        '''</summary>
        Friend Shared ReadOnly Property MSTR_Name() As String
            Get
                Return ResourceManager.GetString("MSTR_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Este recurso utiliza uma biblioteca nativa (não-.NET) da plataforma em execução, e não funciona com o modo de cálculo em paralelo na CPU ativado. por favor desative esse recurso e tente novamente..
        '''</summary>
        Friend Shared ReadOnly Property ParallelPInvokeError() As String
            Get
                Return ResourceManager.GetString("ParallelPInvokeError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Método de Cálculo Entalpia/Entropia/Cp/Cv (0 = Lee-Kesler, 1 = Ideal, 2 = Excesso).
        '''</summary>
        Friend Shared ReadOnly Property PP_ENTH_CP_CALC_METHOD() As String
            Get
                Return ResourceManager.GetString("PP_ENTH_CP_CALC_METHOD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Algoritmo Flash (2 = Definição Global, 0 = LA ELV, 1 = IO ELV, 3 = IO ELLV, 4 = Gibbs ELV, 5 = Gibbs ELLV, 6 = NL ELLV, 7 = NL ESL, 8 = NL Imisc., 9 = LLE Simples).
        '''</summary>
        Friend Shared ReadOnly Property PP_FLASHALGORITHM() As String
            Get
                Return ResourceManager.GetString("PP_FLASHALGORITHM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Algoritmo Flash no Modo Rápido.
        '''</summary>
        Friend Shared ReadOnly Property PP_FLASHALGORITHMFASTMODE() As String
            Get
                Return ResourceManager.GetString("PP_FLASHALGORITHMFASTMODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilizar K ideal na solução trivial.
        '''</summary>
        Friend Shared ReadOnly Property PP_FLASHALGORITHMIDEALKFALLBACK() As String
            Get
                Return ResourceManager.GetString("PP_FLASHALGORITHMIDEALKFALLBACK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usar Regra de Mistura Ideal para Densidade da Phase Líquida (0 = Desativar, 1 = Ativar).
        '''</summary>
        Friend Shared ReadOnly Property PP_IDEAL_MIXRULE_LIQDENS() As String
            Get
                Return ResourceManager.GetString("PP_IDEAL_MIXRULE_LIQDENS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usar Modelo Ideal para Fugacidade da Phase Vapor (0 = Desativar, 1 = Ativar).
        '''</summary>
        Friend Shared ReadOnly Property PP_IDEAL_VAPOR_PHASE_FUG() As String
            Get
                Return ResourceManager.GetString("PP_IDEAL_VAPOR_PHASE_FUG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ignorar limite máximo de salinidade.
        '''</summary>
        Friend Shared ReadOnly Property PP_IGNORE_SALINITY_LIMIT() As String
            Get
                Return ResourceManager.GetString("PP_IGNORE_SALINITY_LIMIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remover limite da fração de vapor (VF &gt;= 0 e VF &lt;= 1) no cálculo flash.
        '''</summary>
        Friend Shared ReadOnly Property PP_IGNORE_VAPOR_FRACTION_LIMIT() As String
            Get
                Return ResourceManager.GetString("PP_IGNORE_VAPOR_FRACTION_LIMIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PH - Tolerância do Loop Externo.
        '''</summary>
        Friend Shared ReadOnly Property PP_PHFELT() As String
            Get
                Return ResourceManager.GetString("PP_PHFELT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PH - Tolerância do Loop Interno.
        '''</summary>
        Friend Shared ReadOnly Property PP_PHFILT() As String
            Get
                Return ResourceManager.GetString("PP_PHFILT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PH - Número Máximo de Iterações no Loop Externo.
        '''</summary>
        Friend Shared ReadOnly Property PP_PHFMEI() As String
            Get
                Return ResourceManager.GetString("PP_PHFMEI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PH - Número Máximo de Iterações no Loop Interno.
        '''</summary>
        Friend Shared ReadOnly Property PP_PHFMII() As String
            Get
                Return ResourceManager.GetString("PP_PHFMII", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usar fator de correção de Poynting para a fugacidade dos componentes na fase líquida (0 = Desativar, 1 = Ativar).
        '''</summary>
        Friend Shared ReadOnly Property PP_POYNTING() As String
            Get
                Return ResourceManager.GetString("PP_POYNTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PS - Tolerância do Loop Externo.
        '''</summary>
        Friend Shared ReadOnly Property PP_PSFELT() As String
            Get
                Return ResourceManager.GetString("PP_PSFELT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PS - Tolerância do Loop Interno.
        '''</summary>
        Friend Shared ReadOnly Property PP_PSFILT() As String
            Get
                Return ResourceManager.GetString("PP_PSFILT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PS - Número Máximo de Iterações no Loop Externo.
        '''</summary>
        Friend Shared ReadOnly Property PP_PSFMEI() As String
            Get
                Return ResourceManager.GetString("PP_PSFMEI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PS - Número Máximo de Iterações no Loop Interno.
        '''</summary>
        Friend Shared ReadOnly Property PP_PSFMII() As String
            Get
                Return ResourceManager.GetString("PP_PSFMII", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PT/PV - Tolerância do Loop Externo.
        '''</summary>
        Friend Shared ReadOnly Property PP_PTFELT() As String
            Get
                Return ResourceManager.GetString("PP_PTFELT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PT/PV - Tolerância do Loop Interno.
        '''</summary>
        Friend Shared ReadOnly Property PP_PTFILT() As String
            Get
                Return ResourceManager.GetString("PP_PTFILT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PT/PV - Número Máximo de Iterações no Loop Externo.
        '''</summary>
        Friend Shared ReadOnly Property PP_PTFMEI() As String
            Get
                Return ResourceManager.GetString("PP_PTFMEI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PT/PV- Número Máximo de Iterações no Loop Interno.
        '''</summary>
        Friend Shared ReadOnly Property PP_PTFMII() As String
            Get
                Return ResourceManager.GetString("PP_PTFMII", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usar Cálculo Rigoroso de Pressões de Bolha e Orvalho para Inicializar o Flash PT (0 = Desativar, 1 = Ativar).
        '''</summary>
        Friend Shared ReadOnly Property PP_RIG_BUB_DEW_FLASH_INIT() As String
            Get
                Return ResourceManager.GetString("PP_RIG_BUB_DEW_FLASH_INIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usar EDE para o Cálculo da Massa Específica da Phase Líquida (0 = Desativar, 1 = Ativar).
        '''</summary>
        Friend Shared ReadOnly Property PP_USE_EOS_LIQDENS() As String
            Get
                Return ResourceManager.GetString("PP_USE_EOS_LIQDENS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usar correção de volume (Peneloux) (0 = Desativar, 1 = Ativar).
        '''</summary>
        Friend Shared ReadOnly Property PP_USE_EOS_VOLUME_SHIFT() As String
            Get
                Return ResourceManager.GetString("PP_USE_EOS_VOLUME_SHIFT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usar Curva Experimental para Cálculo da Densidade (Líquido) (0 = Desativar, 1 = Ativar).
        '''</summary>
        Friend Shared ReadOnly Property PP_USEEXPLIQDENS() As String
            Get
                Return ResourceManager.GetString("PP_USEEXPLIQDENS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usar Curva Experimental para Cálculo da Condutividade Térmica (Líquido) (0 = Desativar, 1 = Ativar).
        '''</summary>
        Friend Shared ReadOnly Property PP_USEEXPLIQTHERMALCOND() As String
            Get
                Return ResourceManager.GetString("PP_USEEXPLIQTHERMALCOND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erro no cálculo Flash..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashError() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O número máximo de iterações no cálculo Flash foi atingido..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashMaxIt() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashMaxIt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PT: Máx Iterações Atingido..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashMaxIt2() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashMaxIt2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PH: Erro no loop interno..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashPHInternalLoopError() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashPHInternalLoopError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PH: Máximo de iterações no loop externo atingido..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashPHMaxExtIt() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashPHMaxExtIt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PH: Máximo de iterações no loop interno atingido..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashPHMaxIntIt() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashPHMaxIntIt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PH: Erro ao calcular temperatura..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlasHPHTempError() As String
            Get
                Return ResourceManager.GetString("PropPack_FlasHPHTempError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O cálculo Flash PSF não é suportado..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashPSFError() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashPSFError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PS: Erro no loop interno..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashPSInternalLoopError() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashPSInternalLoopError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PS: Máximo de iterações no loop externo atingido..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashPSMaxExtIt() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashPSMaxExtIt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PS: Máximo de iterações no loop interno atingido..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashPSMaxIntIt() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashPSMaxIntIt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PS: Erro ao calcular temperatura..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlasHPSTempError() As String
            Get
                Return ResourceManager.GetString("PropPack_FlasHPSTempError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O cálculo Flash PV não é suportado..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashPVNotSupported() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashPVNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O cálculo Flash TH não é suportado..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashTHNotSupported() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashTHNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash PT: Erro ao calcular fração de vapor..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashTPVapFracError() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashTPVapFracError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O algoritmo Flash convergiu para a solução trivial. Tente executar o cálculo em uma condição perturbada de temperatura e/ou pressão ou utilize outro Pacote de Propriedades similar ao atual..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashTrivialSolution() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashTrivialSolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to O cálculo Flash TS não é suportado..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_FlashTSNotSupported() As String
            Get
                Return ResourceManager.GetString("PropPack_FlashTSNotSupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erro no cálculo do fator de compressibilidade..
        '''</summary>
        Friend Shared ReadOnly Property PropPack_ZError() As String
            Get
                Return ResourceManager.GetString("PropPack_ZError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
