C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.exe
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.Automation.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.Interfaces.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.UnitOperations.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.Thermodynamics.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.SharedClasses.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.DrawingTools.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.GlobalSettings.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.XMLSerializer.dll
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /u DWSIM.FlowsheetSolver.dll

C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.Automation.dll
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.Interfaces.dll
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.UnitOperations.dll
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.Thermodynamics.dll
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.SharedClasses.dll
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.DrawingTools.dll
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.GlobalSettings.dll
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.XMLSerializer.dll
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /u DWSIM.FlowsheetSolver.dll