/*
 *                       Yeppp! library implementation
 *                   This file is auto-generated by Peach-Py,
 *        Portable Efficient Assembly Code-generator in Higher-level Python,
 *                  part of the Yeppp! library infrastructure
 * This file is part of Yeppp! library and licensed under the New BSD license.
 * See LICENSE.txt for the full text of the license.
 */

namespace Yeppp
{

	public partial class Math
	{

		internal static void Unbind()
		{
			Math.yepMath_Log_V64f_V64f = null;
			Math.yepMath_Exp_V64f_V64f = null;
			Math.yepMath_Sin_V64f_V64f = null;
			Math.yepMath_Cos_V64f_V64f = null;
			Math.yepMath_Tan_V64f_V64f = null;
			Math.yepMath_EvaluatePolynomial_V32fV32f_V32f = null;
			Math.yepMath_EvaluatePolynomial_V64fV64f_V64f = null;
		}

	}

}
