C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.tlb DWSIM.exe /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.Automation.tlb DWSIM.Automation.dll /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.Interfaces.tlb DWSIM.Interfaces.dll /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.UnitOperations.tlb DWSIM.UnitOperations.dll /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.Thermodynamics.tlb DWSIM.Thermodynamics.dll /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.SharedClasses.tlb DWSIM.SharedClasses.dll /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.DrawingTools.tlb DWSIM.DrawingTools.dll /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.GlobalSettings.tlb DWSIM.GlobalSettings.dll /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.XMLSerializer.tlb DWSIM.XMLSerializer.dll /codebase
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /tlb:DWSIM.FlowsheetSolver.tlb DWSIM.FlowsheetSolver.dll /codebase

C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.tlb DWSIM.exe /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.Automation.tlb DWSIM.Automation.dll /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.Interfaces.tlb DWSIM.Interfaces.dll /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.UnitOperations.tlb DWSIM.UnitOperations.dll /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.Thermodynamics.tlb DWSIM.Thermodynamics.dll /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.SharedClasses.tlb DWSIM.SharedClasses.dll /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.DrawingTools.tlb DWSIM.DrawingTools.dll /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.GlobalSettings.tlb DWSIM.GlobalSettings.dll /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.XMLSerializer.tlb DWSIM.XMLSerializer.dll /codebase
C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe /tlb:DWSIM.FlowsheetSolver.tlb DWSIM.FlowsheetSolver.dll /codebase