/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AbstractState : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AbstractState(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AbstractState obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AbstractState() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CoolPropPINVOKE.delete_AbstractState(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public static AbstractState factory(string backend, string fluid_names) {
    global::System.IntPtr cPtr = CoolPropPINVOKE.AbstractState_factory__SWIG_0(backend, fluid_names);
    AbstractState ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractState(cPtr, false);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static AbstractState factory(string backend, SWIGTYPE_p_std__vectorT_std__string_t fluid_names) {
    global::System.IntPtr cPtr = CoolPropPINVOKE.AbstractState_factory__SWIG_1(backend, SWIGTYPE_p_std__vectorT_std__string_t.getCPtr(fluid_names));
    AbstractState ret = (cPtr == global::System.IntPtr.Zero) ? null : new AbstractState(cPtr, false);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool using_mole_fractions() {
    bool ret = CoolPropPINVOKE.AbstractState_using_mole_fractions(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool using_mass_fractions() {
    bool ret = CoolPropPINVOKE.AbstractState_using_mass_fractions(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool using_volu_fractions() {
    bool ret = CoolPropPINVOKE.AbstractState_using_volu_fractions(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void update(input_pairs input_pair, double Value1, double Value2) {
    CoolPropPINVOKE.AbstractState_update(swigCPtr, (int)input_pair, Value1, Value2);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void set_mole_fractions(SWIGTYPE_p_std__vectorT_CoolPropDbl_t mole_fractions) {
    CoolPropPINVOKE.AbstractState_set_mole_fractions__SWIG_0(swigCPtr, SWIGTYPE_p_std__vectorT_CoolPropDbl_t.getCPtr(mole_fractions));
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void set_mass_fractions(SWIGTYPE_p_std__vectorT_CoolPropDbl_t mass_fractions) {
    CoolPropPINVOKE.AbstractState_set_mass_fractions__SWIG_0(swigCPtr, SWIGTYPE_p_std__vectorT_CoolPropDbl_t.getCPtr(mass_fractions));
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void set_volu_fractions(SWIGTYPE_p_std__vectorT_CoolPropDbl_t mass_fractions) {
    CoolPropPINVOKE.AbstractState_set_volu_fractions__SWIG_0(swigCPtr, SWIGTYPE_p_std__vectorT_CoolPropDbl_t.getCPtr(mass_fractions));
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual SWIGTYPE_p_std__vectorT_CoolPropDbl_t get_mole_fractions() {
    SWIGTYPE_p_std__vectorT_CoolPropDbl_t ret = new SWIGTYPE_p_std__vectorT_CoolPropDbl_t(CoolPropPINVOKE.AbstractState_get_mole_fractions(swigCPtr), false);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_std__string_t fluid_names() {
    SWIGTYPE_p_std__vectorT_std__string_t ret = new SWIGTYPE_p_std__vectorT_std__string_t(CoolPropPINVOKE.AbstractState_fluid_names(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool clear() {
    bool ret = CoolPropPINVOKE.AbstractState_clear(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void set_mole_fractions(DoubleVector mole_fractions) {
    CoolPropPINVOKE.AbstractState_set_mole_fractions__SWIG_1(swigCPtr, DoubleVector.getCPtr(mole_fractions));
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_mass_fractions(DoubleVector mass_fractions) {
    CoolPropPINVOKE.AbstractState_set_mass_fractions__SWIG_1(swigCPtr, DoubleVector.getCPtr(mass_fractions));
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set_volu_fractions(DoubleVector volu_fractions) {
    CoolPropPINVOKE.AbstractState_set_volu_fractions__SWIG_1(swigCPtr, DoubleVector.getCPtr(volu_fractions));
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual SS get_reducing_state() {
    SS ret = new SS(CoolPropPINVOKE.AbstractState_get_reducing_state(swigCPtr), false);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SS get_state(string state) {
    SS ret = new SS(CoolPropPINVOKE.AbstractState_get_state(swigCPtr, state), false);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Tmin() {
    double ret = CoolPropPINVOKE.AbstractState_Tmin(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Tmax() {
    double ret = CoolPropPINVOKE.AbstractState_Tmax(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double pmax() {
    double ret = CoolPropPINVOKE.AbstractState_pmax(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Ttriple() {
    double ret = CoolPropPINVOKE.AbstractState_Ttriple(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public phases phase() {
    phases ret = (phases)CoolPropPINVOKE.AbstractState_phase(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void specify_phase(phases phase) {
    CoolPropPINVOKE.AbstractState_specify_phase(swigCPtr, (int)phase);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public void unspecify_phase() {
    CoolPropPINVOKE.AbstractState_unspecify_phase(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public double T_critical() {
    double ret = CoolPropPINVOKE.AbstractState_T_critical(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double T_reducing() {
    double ret = CoolPropPINVOKE.AbstractState_T_reducing(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double p_critical() {
    double ret = CoolPropPINVOKE.AbstractState_p_critical(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomolar_critical() {
    double ret = CoolPropPINVOKE.AbstractState_rhomolar_critical(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomass_critical() {
    double ret = CoolPropPINVOKE.AbstractState_rhomass_critical(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomolar_reducing() {
    double ret = CoolPropPINVOKE.AbstractState_rhomolar_reducing(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomass_reducing() {
    double ret = CoolPropPINVOKE.AbstractState_rhomass_reducing(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double p_triple() {
    double ret = CoolPropPINVOKE.AbstractState_p_triple(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string name() {
    string ret = CoolPropPINVOKE.AbstractState_name(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double keyed_output(int key) {
    double ret = CoolPropPINVOKE.AbstractState_keyed_output(swigCPtr, key);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double trivial_keyed_output(int key) {
    double ret = CoolPropPINVOKE.AbstractState_trivial_keyed_output(swigCPtr, key);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double saturated_liquid_keyed_output(parameters key) {
    double ret = CoolPropPINVOKE.AbstractState_saturated_liquid_keyed_output(swigCPtr, (int)key);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double saturated_vapor_keyed_output(parameters key) {
    double ret = CoolPropPINVOKE.AbstractState_saturated_vapor_keyed_output(swigCPtr, (int)key);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double T() {
    double ret = CoolPropPINVOKE.AbstractState_T(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomolar() {
    double ret = CoolPropPINVOKE.AbstractState_rhomolar(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double rhomass() {
    double ret = CoolPropPINVOKE.AbstractState_rhomass(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double p() {
    double ret = CoolPropPINVOKE.AbstractState_p(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Q() {
    double ret = CoolPropPINVOKE.AbstractState_Q(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double tau() {
    double ret = CoolPropPINVOKE.AbstractState_tau(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double delta() {
    double ret = CoolPropPINVOKE.AbstractState_delta(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double molar_mass() {
    double ret = CoolPropPINVOKE.AbstractState_molar_mass(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double acentric_factor() {
    double ret = CoolPropPINVOKE.AbstractState_acentric_factor(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double gas_constant() {
    double ret = CoolPropPINVOKE.AbstractState_gas_constant(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Bvirial() {
    double ret = CoolPropPINVOKE.AbstractState_Bvirial(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dBvirial_dT() {
    double ret = CoolPropPINVOKE.AbstractState_dBvirial_dT(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Cvirial() {
    double ret = CoolPropPINVOKE.AbstractState_Cvirial(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double dCvirial_dT() {
    double ret = CoolPropPINVOKE.AbstractState_dCvirial_dT(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double compressibility_factor() {
    double ret = CoolPropPINVOKE.AbstractState_compressibility_factor(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double hmolar() {
    double ret = CoolPropPINVOKE.AbstractState_hmolar(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double hmass() {
    double ret = CoolPropPINVOKE.AbstractState_hmass(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double smolar() {
    double ret = CoolPropPINVOKE.AbstractState_smolar(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double smass() {
    double ret = CoolPropPINVOKE.AbstractState_smass(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double umolar() {
    double ret = CoolPropPINVOKE.AbstractState_umolar(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double umass() {
    double ret = CoolPropPINVOKE.AbstractState_umass(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cpmolar() {
    double ret = CoolPropPINVOKE.AbstractState_cpmolar(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cpmass() {
    double ret = CoolPropPINVOKE.AbstractState_cpmass(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cp0molar() {
    double ret = CoolPropPINVOKE.AbstractState_cp0molar(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cp0mass() {
    double ret = CoolPropPINVOKE.AbstractState_cp0mass(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cvmolar() {
    double ret = CoolPropPINVOKE.AbstractState_cvmolar(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double cvmass() {
    double ret = CoolPropPINVOKE.AbstractState_cvmass(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double gibbsmolar() {
    double ret = CoolPropPINVOKE.AbstractState_gibbsmolar(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double speed_sound() {
    double ret = CoolPropPINVOKE.AbstractState_speed_sound(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double isothermal_compressibility() {
    double ret = CoolPropPINVOKE.AbstractState_isothermal_compressibility(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double isobaric_expansion_coefficient() {
    double ret = CoolPropPINVOKE.AbstractState_isobaric_expansion_coefficient(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double fugacity_coefficient(int i) {
    double ret = CoolPropPINVOKE.AbstractState_fugacity_coefficient(swigCPtr, i);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CoolPropDbl_t mole_fractions_liquid() {
    SWIGTYPE_p_std__vectorT_CoolPropDbl_t ret = new SWIGTYPE_p_std__vectorT_CoolPropDbl_t(CoolPropPINVOKE.AbstractState_mole_fractions_liquid(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_CoolPropDbl_t mole_fractions_vapor() {
    SWIGTYPE_p_std__vectorT_CoolPropDbl_t ret = new SWIGTYPE_p_std__vectorT_CoolPropDbl_t(CoolPropPINVOKE.AbstractState_mole_fractions_vapor(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl first_partial_deriv(parameters Of, parameters Wrt, parameters Constant) {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_first_partial_deriv(swigCPtr, (int)Of, (int)Wrt, (int)Constant), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl second_partial_deriv(parameters Of1, parameters Wrt1, parameters Constant1, parameters Of2, parameters Constant2) {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_second_partial_deriv(swigCPtr, (int)Of1, (int)Wrt1, (int)Constant1, (int)Of2, (int)Constant2), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl first_saturation_deriv(parameters Of1, parameters Wrt1) {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_first_saturation_deriv(swigCPtr, (int)Of1, (int)Wrt1), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl second_saturation_deriv(parameters Of1, parameters Wrt1, parameters Of2, parameters Wrt2) {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_second_saturation_deriv(swigCPtr, (int)Of1, (int)Wrt1, (int)Of2, (int)Wrt2), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double first_two_phase_deriv(parameters Of, parameters Wrt, parameters Constant) {
    double ret = CoolPropPINVOKE.AbstractState_first_two_phase_deriv(swigCPtr, (int)Of, (int)Wrt, (int)Constant);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double second_two_phase_deriv(parameters Of, parameters Wrt1, parameters Constant1, parameters Wrt2, parameters Constant2) {
    double ret = CoolPropPINVOKE.AbstractState_second_two_phase_deriv(swigCPtr, (int)Of, (int)Wrt1, (int)Constant1, (int)Wrt2, (int)Constant2);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double first_two_phase_deriv_splined(parameters Of, parameters Wrt, parameters Constant, double x_end) {
    double ret = CoolPropPINVOKE.AbstractState_first_two_phase_deriv_splined(swigCPtr, (int)Of, (int)Wrt, (int)Constant, x_end);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void build_phase_envelope(string type) {
    CoolPropPINVOKE.AbstractState_build_phase_envelope(swigCPtr, type);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
  }

  public PED get_phase_envelope_data() {
    PED ret = new PED(CoolPropPINVOKE.AbstractState_get_phase_envelope_data(swigCPtr), false);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool has_melting_line() {
    bool ret = CoolPropPINVOKE.AbstractState_has_melting_line(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double melting_line(int param, int given, double value) {
    double ret = CoolPropPINVOKE.AbstractState_melting_line(swigCPtr, param, given, value);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double saturation_ancillary(parameters param, int Q, parameters given, double value) {
    double ret = CoolPropPINVOKE.AbstractState_saturation_ancillary(swigCPtr, (int)param, Q, (int)given, value);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double viscosity() {
    double ret = CoolPropPINVOKE.AbstractState_viscosity(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double conductivity() {
    double ret = CoolPropPINVOKE.AbstractState_conductivity(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double surface_tension() {
    double ret = CoolPropPINVOKE.AbstractState_surface_tension(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double Prandtl() {
    double ret = CoolPropPINVOKE.AbstractState_Prandtl(swigCPtr);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl alpha0() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_alpha0(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl dalpha0_dDelta() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_dalpha0_dDelta(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl dalpha0_dTau() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_dalpha0_dTau(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d2alpha0_dDelta2() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d2alpha0_dDelta2(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d2alpha0_dDelta_dTau() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d2alpha0_dDelta_dTau(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d2alpha0_dTau2() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d2alpha0_dTau2(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d3alpha0_dTau3() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d3alpha0_dTau3(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d3alpha0_dDelta_dTau2() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d3alpha0_dDelta_dTau2(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d3alpha0_dDelta2_dTau() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d3alpha0_dDelta2_dTau(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d3alpha0_dDelta3() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d3alpha0_dDelta3(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl alphar() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_alphar(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl dalphar_dDelta() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_dalphar_dDelta(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl dalphar_dTau() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_dalphar_dTau(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d2alphar_dDelta2() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d2alphar_dDelta2(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d2alphar_dDelta_dTau() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d2alphar_dDelta_dTau(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d2alphar_dTau2() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d2alphar_dTau2(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d3alphar_dDelta3() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d3alphar_dDelta3(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d3alphar_dDelta2_dTau() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d3alphar_dDelta2_dTau(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d3alphar_dDelta_dTau2() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d3alphar_dDelta_dTau2(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CoolPropDbl d3alphar_dTau3() {
    SWIGTYPE_p_CoolPropDbl ret = new SWIGTYPE_p_CoolPropDbl(CoolPropPINVOKE.AbstractState_d3alphar_dTau3(swigCPtr), true);
    if (CoolPropPINVOKE.SWIGPendingException.Pending) throw CoolPropPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
