/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum configuration_keys {
  NORMALIZE_GAS_CONSTANTS,
  CRITICAL_WITHIN_1UK,
  CRITICAL_SPLINES_ENABLED,
  ALTERNATIVE_REFPROP_PATH,
  ALTERNATIVE_REFPROP_HMX_BNC_PATH,
  MAXIMUM_TABLE_DIRECTORY_SIZE_IN_GB
}
