/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum input_pairs {
  INPUT_PAIR_INVALID = 0,
  QT_INPUTS,
  PQ_INPUTS,
  QSmolar_INPUTS,
  QSmass_INPUTS,
  HmolarQ_INPUTS,
  HmassQ_INPUTS,
  PT_INPUTS,
  DmassT_INPUTS,
  DmolarT_INPUTS,
  HmolarT_INPUTS,
  HmassT_INPUTS,
  SmolarT_INPUTS,
  SmassT_INPUTS,
  TUmolar_INPUTS,
  TUmass_INPUTS,
  DmassP_INPUTS,
  DmolarP_INPUTS,
  HmassP_INPUTS,
  HmolarP_INPUTS,
  PSmass_INPUTS,
  PSmolar_INPUTS,
  PUmass_INPUTS,
  PUmolar_INPUTS,
  HmassSmass_INPUTS,
  HmolarSmolar_INPUTS,
  SmassUmass_INPUTS,
  SmolarUmolar_INPUTS,
  DmassHmass_INPUTS,
  DmolarHmolar_INPUTS,
  DmassSmass_INPUTS,
  DmolarSmolar_INPUTS,
  DmassUmass_INPUTS,
  DmolarUmolar_INPUTS
}
