/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum phases {
  iphase_liquid,
  iphase_supercritical,
  iphase_supercritical_gas,
  iphase_supercritical_liquid,
  iphase_critical_point,
  iphase_gas,
  iphase_twophase,
  iphase_unknown,
  iphase_not_imposed
}
