#!/bin/sh

# exp_lgN_xthN: calculate thermodynamic properties along a mixture
# 2-phase isentrope (i.e., feed output of exp_lgN to xthN)
# usage: see below

if [ $# -lt 1 ]
then
  echo "usage: exp_lgN_xthN \"PROPERTIES\" [TMP] <INFILE >OUTFILE"
  echo "       PROPERTIES: symbols of properties, e.g., kT or Sm%16.8e"
  echo "       TMP: temporary file"
  echo "       INFILE: output file of exp_lgN"
  echo "       hint: encode space as \\040, e.g., Ar\\040Sr\\040p"
  exit 1
fi

if [ $# -eq 2 ]
then
  tmp=$2
  tmpL=${tmp}_L
  tmpG=${tmp}_G
  tmpE=${tmp}_E
else
  tmpL=tmpL$$
  tmpG=tmpG$$
  tmpE=tmpE$$
fi


# The ThermoC programs mark the begin and the end of output tables by "+"
# and "-", respectively.

awk -v fileL=$tmpL -v fileG=$tmpG -v thd=$1 -v fileE=$tmpE '
BEGIN	{ mode = 0;
	  m = 0;
	  n = 0;
	}
/component/	{
	  component[n++] = $3;
	}
/equation/	{
	  eos = $4;
	  getline;
	  print eos, $3 >fileE;
	}
/binary/	{
	  getline;
	  set[m++] = $3;
	}
/^-$/	{ mode = 0; }
/^\+$/	{ mode = 1;
	  getline;			// skip table heading
	  getline;
	  getline;
	  print n >fileL
	  print n >fileG
	  for (i = 0; i < n; i++) print component[i] >>fileL;
	  for (i = 0; i < n; i++) print component[i] >>fileG;
	  for (i = 0; i < m; i++) print set[i] >>fileL;
	  for (i = 0; i < m; i++) print set[i] >>fileG;
	  print "V" >>fileL;
	  print "V" >>fileG;
	  print thd >>fileL;
	  print thd >>fileG;
	}
	{ if (mode) {
	    for (i = 4; i < 4 + n; i++) print $i >>fileL;
	    print $3, $1 >>fileL;
	    for (i = 5 + n; i < 5 + 2 * n; i++) print $i >>fileG;
	    i = 4 + n;
	    print $i, $1 >>fileG;
	  }
	}
END	{ fflush(fileL);
	  fflush(fileG);
	  fflush(fileE);
	}
'

eos=`cat $tmpE`

echo "==========================================================================="
echo "SATURATED LIQUID"
xthN $eos <$tmpL 2>/dev/null
echo
echo "==========================================================================="
echo "SATURATED VAPOUR"
xthN $eos <$tmpG 2>/dev/null
rm $tmpL $tmpG $tmpE
exit 0
