//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum backends {
  INVALID_BACKEND = 0,
  HEOS_BACKEND_PURE,
  HEOS_BACKEND_MIX,
  REFPROP_BACKEND_PURE,
  REFPROP_BACKEND_MIX,
  INCOMP_BACKEND,
  IF97_BACKEND,
  TREND_BACKEND,
  TTSE_BACKEND,
  BICUBIC_BACKEND,
  SRK_BACKEND,
  PR_BACKEND,
  VTPR_BACKEND,
  PCSAFT_BACKEND
}
