//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum backend_families {
  INVALID_BACKEND_FAMILY = 0,
  HEOS_BACKEND_FAMILY,
  REFPROP_BACKEND_FAMILY,
  INCOMP_BACKEND_FAMILY,
  IF97_BACKEND_FAMILY,
  TREND_BACKEND_FAMILY,
  TTSE_BACKEND_FAMILY,
  BICUBIC_BACKEND_FAMILY,
  SRK_BACKEND_FAMILY,
  PR_BACKEND_FAMILY,
  VTPR_BACKEND_FAMILY,
  PCSAFT_BACKEND_FAMILY
}
