//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ConfigurationDataTypes {
  CONFIGURATION_NOT_DEFINED_TYPE = 0,
  CONFIGURATION_BOOL_TYPE,
  CONFIGURATION_DOUBLE_TYPE,
  CONFIGURATION_INTEGER_TYPE,
  CONFIGURATION_STRING_TYPE,
  CONFIGURATION_ENDOFLIST_TYPE
}
